        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 18 06:09:37 2012
        MODULE GET_GADGET_FILE__genmod
          INTERFACE 
            SUBROUTINE GET_GADGET_FILE(PART_FILE,IFILE,N_I,NPART_IN_FILE&
     &)
              CHARACTER(LEN=120) :: PART_FILE
              INTEGER(KIND=4) :: IFILE
              INTEGER(KIND=4) :: N_I
              INTEGER(KIND=4) :: NPART_IN_FILE
            END SUBROUTINE GET_GADGET_FILE
          END INTERFACE 
        END MODULE GET_GADGET_FILE__genmod
