        !COMPILER-GENERATED INTERFACE MODULE: Wed Apr 18 06:09:38 2012
        MODULE READ_MULTI_SNAPS__genmod
          INTERFACE 
            SUBROUTINE READ_MULTI_SNAPS(PART_FILE)
              CHARACTER(LEN=180) :: PART_FILE
            END SUBROUTINE READ_MULTI_SNAPS
          END INTERFACE 
        END MODULE READ_MULTI_SNAPS__genmod
