# ===========================================================
# Parameter File for pyc2ray.
#
# Only the currently required parameters are included, as
# more features of C2Ray are ported to pyc2ray, the relevant
# parameters will be included here.
# ===========================================================

# ------------------------------------------
# Parameters to set up the simulation volume
# ------------------------------------------
Grid:
  # Box size in comoving Mpc/h
  boxsize: 200 # Mpc/h
  # boolean variable to indicate if resuming a simulation (no need to change zred_0)
  resume: 0

# --------------------------------------------------------------------
# (Initial) properties of physical quantities in the simulation volume
# --------------------------------------------------------------------
Material:
  # Initial Temperature of the grid
  temp0: 1e4
  # Initial Ionized fraction of the grid
  xh0: 2.0e-4
  # Constant average density, comoving value. Used only by the test case
  # this value is scaled to zred_0 (even in non-cosmological mode)
  avg_dens: 1.981e-07

# --------------------------------
# Miscellaneous physical constants
# --------------------------------
CGS:
  # Hydrogen recombination parameter (power law index)
  albpow: -0.7  #in the old code -0.79
  # Hydrogen recombination parameter (value at 10^4 K)
  bh00: 2.59e-13 # OTS value, alpha_B
  # Helium0 recombination parameter (power law index)
  alcpow: -0.672
  # Hydrogen ionization energy (in eV)
  eth0: 13.598
  #Helium I ionization energy (in eV)
  ethe0: 24.587
  # Helium II ionization energy (in eV)
  ethe1: 54.416
  # Hydrogen collisional ionization parameter 1
  xih0: 1.0
  # Hydrogen collisional ionization parameter 2
  fh0: 0.83
  # ...
  colh0_fact: 1.3e-8

# ------------------
# Element abundances
# ------------------
Abundances:
  # Hydrogen Abundance
  abu_h: 0.926
  # Helium Abundance
  abu_he: 0.074    # 1 abu_he: 0.08 #  for EoR KP sims
  # Carbon Abundance
  abu_c: 7.1e-7

# ------------------------------------
# Parameters governing photoionization
# ------------------------------------
Photo:
  # HI cross section at its ionzing frequency
  sigma_HI_at_ion_freq: 6.30e-18
  # Minimum optical depth for tables
  minlogtau: -20
  # Maximum optical depth for tables
  maxlogtau: 4
  # Number of table points
  NumTau: 2000
  # Whether or not to use grey opacity (i.e. cross-section is frequency-independent)
  grey: 0
  # Type of source to use
  SourceType: blackbody
  # Whether to compute heating rates arrays (NOT USED BY CHEMISTRY SO FAR)
  compute_heating_rates: 0

# ------------------------------------
# Parameters of the radiation sinks
# ------------------------------------
Sinks:
  # define the clumping model to use (can be 'constant', 'redshift', 'density' or 'stochastic')
  clumping_model: 'constant'
  # define clumping factor for the constant model
  clumping: 1.0
  # define the mean-free-path model to use (can be 'constant' or 'Worseck2014')
  mfp_model: 'Worseck2014'
  # Constant value of maximum comoving distance for photons from source, Type 3 LLS in original C2Ray (to not use this, set to a value >> boxsize)
  R_max_cMpc: 15.0
  # free parameter for the Worseck2014 mean-free-path model in cMpc units
  A_mfp: 225.0
  # spectral index of the Worseck2014 mean-free-path model redshift evolution
  eta_mfp: -8.8

# --------------------------------
# Parameters for Black Body source
# --------------------------------
BlackBodySource:
  # Effective temperature of Black Body source
  Teff: 5e4
  # Power-law index for the frequency dependence of the photoionization cross section
  cross_section_pl_index: 2.8

Sources:
  # stellar-to-halo mass relation: 'fgamma' for classical mass independent model, 'dpl' for double power law (Schneider, Giri, Mirocha 2021).
  fstar_kind: 'dpl' 
  # efficiency High-Mass Atomically Cooling Halo (HMACH) - used only for fstar_kind: 'fgamma'
  fgamma_hm: 30
  # efficiency Low-Mass Atomically Cooling Halo (LMACH)
  fgamma_lm: 0.
  # Double power law parameter - these are used only when fstar_kind: 'dpl'
  Nion: 4.0
  f0: 1.0 
  Mt: 1e8 
  Mp: 1e10
  g1: -0.3
  g2: -0.3
  g3: 0
  g4: -0.0
  # Photons escaping fraction: 'constant' for mass independent model, 'power' for a power law mass dependent factor
  fesc_model: 'constant'
  f0_esc: 1.0
  Mp_esc: 1e10
  al_esc: -0.5
  # define the accreation model (can be 'constant' or 'EXP')
  accretion_model: 'EXP'
  # accreation rate parameter (see Schneider+ 2021)
  alpha_h: 0.79

# -----------------------
# Cosmological Parameters
# -----------------------
Cosmology:
  # Global flag to use cosmology
  cosmological: 1
  # Reduced Hubble constant
  h: 0.67
  # Omega matter t=0
  Omega0: 0.32
  # Omega baryon t=0
  Omega_B: 0.044
  # Temperature of CMB in Kelvins
  cmbtemp: 2.726
  # Initial redshift of the simulation
  zred_0: 21.481530

  # N.B. : Planck 18
  #  h: 0.6766
  #  Omega0: 0.30966
  #  Omega_B: 0.04897
  #  cmbtemp: 2.7255

# ------------
# Output setup
# ------------
Output:
  # Directory where results and log files are stored (don't forget slash at end)
  results_basename: /scratch/snx3000/mibianco/results_c2ray/200Mpc_fstar_256/200Mpc_Nion_4_f0_1_Mt_1e8_Mp_1e10_g1_m03_g2_m03_g3_0_g4_0_alesc_m05/
  # Directory where inputs files are stored (set to None for test case)
  inputs_basename: /store/ska/sk015/CDM_200Mpc_2048/
  # Directory where inputs files are stored (set to None for test case)
  sources_basename: /store/ska/sk015/CDM_200Mpc_2048/haloes/
  # Directory where inputs files are stored (set to None for test case)
  density_basename: /store/ska/sk015/CDM_200Mpc_2048/grids/nc256/
  # Name of the log file to write
  logfile: pyC2Ray.log

# -------------------------
# Parameters for raytracing
# -------------------------
Raytracing:
  # Photon loss fraction for the subbox algorithm (not used if using ASORA)
  loss_fraction: 1e-2
  # Size increase of subboxes around sources (not used if using ASORA)
  subboxsize: 5
  # Maximum subbox size for the subbox algorithm (not used if using ASORA)
  max_subbox: 1000
  # Source batch size, i.e. number of sources handled in parallel on the GPU.
  # Speeds up computation but increases memory usage
  source_batch_size: 96
  # Which fraction of the cells can be left unconverged
  convergence_fraction: 1e-4
