name: Python application

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "pyproject.toml"
      - "pyc2ray/**.py"
      - "tests/**.py"
      - "src/**.f90"
      - "src/**.cu"
      - "src/**.cuh"
      - "**/meson.build"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff clang-format

    - name: Check code format
      run: ruff format --check pyc2ray/ tests/

    - name: Check code style
      run: ruff check --extend-select I --output-format=concise pyc2ray/ tests/

    # - name: Setup CUDA
    #   uses: Jimver/cuda-toolkit@v0.2.28
    #   with:
    #     cuda: "12.5.0"

    - name: Install MPI library
      run: sudo apt install libopenmpi-dev

    - name: Build with setuptools
      run: pip install .

    - name: Build wheel
      run: |
        pip install build
        python -m build

    - name: Run tests
      run: |
        pip install pytest
        pytest tests/
