name: Lint code

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/lint.yml
      - pyproject.toml
      - pyc2ray/**.py
      - tests/**.py
      - src/**.f90
      - src/**.cu
      - src/**.cuh
      - '**/meson.build'

permissions:
  contents: read

jobs:
  lintpy:
    name: Lint Python
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v5
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v6
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install linters and pyC2Ray
        run: pip install ruff mypy numpy>=2
      - name: Check Python code format
        run: ruff format --check pyc2ray/ tests/
      - name: Check Python code style
        run: ruff check --extend-select I --output-format=concise pyc2ray/ tests/
      - name: Check Python code type annotations
        run: mypy pyc2ray/ tests/
        if: '${{ !(matrix.os == ''ubuntu-22.04'') }}'

  lintcpp:
    name: Lint C++ and CUDA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install clang-format
        run: pip install "clang-format>=22"
      - name: Check C++ and CUDA code style
        run: find src/ -regex '.*\.\(cu\|cuh\|cpp\|h\)' | xargs clang-format -n -Werror

  lintmeson:
    name: Lint meson
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install meson
        run: pip install meson
      - name: Check meson code style
        run: find . -name meson.build | xarts meson format -q
